name: tests-and-allure-ghpages
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write   # => necesario para pushear a gh-pages

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Java (Allure CLI necesita Java)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run tests (solo tu login)
        run: |
          pytest tests/test_pom_login.py -v --alluredir=results

      - name: Debug results
        run: |
          ls -la results || true

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Allure CLI
        run: npm i -g allure-commandline

      - name: Generate Allure report
        run: allure generate results -o reports --clean

      - name: Ensure index.html exists
        run: test -f reports/index.html

      # (Opcional) artifacts para descargar
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports

      # Publicar a gh-pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
          publish_branch: gh-pages
          force_orphan: true   # crea historial limpio (opcional)
